<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on 2019年 04月 10日 星期三 11:56:20 CST.

define('DOMJUDGE_VERSION', '6.0.3');

define('BINDIR',      '/home/yancy/domjudge/domserver/bin');
define('ETCDIR',      '/home/yancy/domjudge/domserver/etc');
define('WWWDIR',      '/home/yancy/domjudge/domserver/www');
define('WEBAPPDIR',   '/home/yancy/domjudge/domserver/webapp');
define('LIBDIR',      '/home/yancy/domjudge/domserver/lib');
define('SQLDIR',      '/home/yancy/domjudge/domserver/sql');
define('LIBVENDORDIR','/home/yancy/domjudge/domserver/lib/vendor');
define('LIBWWWDIR',   '/home/yancy/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/home/yancy/domjudge/domserver/lib/submit');
define('LOGDIR',      '/home/yancy/domjudge/domserver/log');
define('RUNDIR',      '/home/yancy/domjudge/domserver/run');
define('TMPDIR',      '/home/yancy/domjudge/domserver/tmp');
define('SUBMITDIR',   '/home/yancy/domjudge/domserver/submissions');

define('BASEURL',     '127.0.0.1');

define('SUBMITCLIENT_ENABLED', 'yes');
